# Generated by Django 4.2.3 on 2023-07-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BN", "Basic Needs"),
                            ("RF", "Recreation and Fun"),
                            ("CE", "Culture and Extras"),
                        ],
                        max_length=2,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("date", models.DateField()),
            ],
        ),
    ]
