# Generated by Django 4.2.3 on 2023-07-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kakebo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
