# Generated by Django 4.2.3 on 2023-07-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kakebo_app", "0002_expense_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="store",
            field=models.CharField(default="", max_length=50),
        ),
    ]
