# Generated by Django 4.2.3 on 2023-07-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kakebo_app", "0004_rename_store_expense_vendor_alter_expense_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="description",
        ),
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "Euro"),
                    ("USD", "US Dollar"),
                    ("PLN", "Polish Zloty"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CNY", "Chinese Yuan"),
                    ("CAD", "Canadian Dollar"),
                    ("AUD", "Australian Dollar"),
                    ("NZD", "New Zealand Dollar"),
                    ("CHF", "Swiss Franc"),
                    ("SEK", "Swedish Krona"),
                    ("NOK", "Norwegian Krone"),
                    ("DKK", "Danish Krone"),
                    ("MXN", "Mexican Peso"),
                    ("SGD", "Singapore Dollar"),
                    ("HKD", "Hong Kong Dollar"),
                    ("KRW", "South Korean Won"),
                    ("TRY", "Turkish Lira"),
                    ("RUB", "Russian Ruble"),
                    ("INR", "Indian Rupee"),
                ],
                default="EUR",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="expense",
            name="vendor",
            field=models.CharField(max_length=100),
        ),
    ]
